// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package proto.chat;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.chat.Empty)
    com.google.protobuf.MessageOrBuilder {
}
